name: Mirror DockerHub

on:
  schedule:
    - cron: '0 0 1,15 * *'
  workflow_dispatch:
    inputs:
      IMAGE_NAME:
        description: 'The name of Image to be Mirrored'
        type: choice
        options:
          - ''
          - 'dotnet-sdk'
          - 'grafana'
          - 'descheduler'
        default: ''

jobs:
  mirror:
    name: Mirror
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: dotnet-sdk
            repo: mcr.microsoft.com
            image: dotnet/sdk
            dest-image: dotnet-sdk
            multi-arch: system
          - name: grafana
            repo: docker.io
            image: grafana/grafana
            dest-image: grafana
            multi-arch: system
          - name: descheduler
            repo: registry.k8s.io
            image: descheduler/descheduler
            dest-image: descheduler
            multi-arch: system
    steps:
      - uses: actions/checkout@v4
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      
      - name: Log in to My AlibabaACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_ACCESS_TOKEN }}

      - name: Set up skopeo environment         
#        uses: balena-io-experimental/setup-skopeo-action@main
        uses: warjiang/setup-skopeo@main
        with:
          version: latest
          
      - name: 'Skopeo copy images to My AlibabaACR'
        if: ${{ github.event.inputs.IMAGE_NAME == '' || github.event.inputs.IMAGE_NAME == matrix.name }}
        run: |
          skopeo --version
          for tag in $(cat ./images/${{ matrix.name }}); do
            skopeo copy --multi-arch ${{ matrix.multi-arch || 'system' }}  \
              docker://${{ matrix.repo }}/${{ matrix.image }}:$tag \
              docker://${{ secrets.ACR_SERVER }}/${{ secrets.ACR_REPOSITORY }}/${{ matrix.dest-image || matrix.image }}:$tag
          done
          
